/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 3118 L4
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstInput = new javax.swing.JTextField();
        addVar = new javax.swing.JRadioButton();
        subVar = new javax.swing.JRadioButton();
        divVar = new javax.swing.JRadioButton();
        mulVar = new javax.swing.JRadioButton();
        secondInput = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("some value");

        firstInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstInputActionPerformed(evt);
            }
        });

        addVar.setText("+");
        addVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVarMouseClicked(evt);
            }
        });
        addVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVarActionPerformed(evt);
            }
        });

        subVar.setText("-");
        subVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subVarMouseClicked(evt);
            }
        });
        subVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subVarActionPerformed(evt);
            }
        });

        divVar.setText("/");
        divVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divVarMouseClicked(evt);
            }
        });
        divVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divVarActionPerformed(evt);
            }
        });

        mulVar.setText("*");
        mulVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulVarMouseClicked(evt);
            }
        });
        mulVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulVarActionPerformed(evt);
            }
        });

        secondInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondInputActionPerformed(evt);
            }
        });

        calculateBtn.setText("Calculate");
        calculateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateBtnMouseClicked(evt);
            }
        });
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(firstInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mulVar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addComponent(calculateBtn))
                                        .addComponent(secondInput, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addVar)
                                        .addComponent(subVar)
                                        .addComponent(divVar))))
                            .addGap(30, 30, 30)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(status)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstInput, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subVar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(secondInput, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(calculateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divVar)
                        .addGap(11, 11, 11)
                        .addComponent(mulVar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(status)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstInputActionPerformed

    private void addVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVarActionPerformed

    private void subVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subVarActionPerformed

    private void divVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divVarActionPerformed

    private void addVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVarMouseClicked
        /**
         * Here will be checkd if first button is check [ of couse it is a rado button ] 
         * 
         */
        if(addVar.isSelected()){
            subVar.setSelected(false);
            divVar.setSelected(false);
            mulVar.setSelected(false);
        }
        
        
    }//GEN-LAST:event_addVarMouseClicked

    private void subVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subVarMouseClicked
        if(subVar.isSelected()){
            addVar.setSelected(false);
            mulVar.setSelected(false);
            divVar.setSelected(false);
        }
    }//GEN-LAST:event_subVarMouseClicked

    private void divVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divVarMouseClicked
        if(divVar.isSelected()){
            addVar.setSelected(false);
            mulVar.setSelected(false);
            subVar.setSelected(false);
        }
    }//GEN-LAST:event_divVarMouseClicked

    private void mulVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulVarMouseClicked
        if(mulVar.isSelected()){
            addVar.setSelected(false);
            subVar.setSelected(false);
            divVar.setSelected(false);
        }
    }//GEN-LAST:event_mulVarMouseClicked

    private void calculateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateBtnMouseClicked
        String input = firstInput.getText();
        
        
        String Secondinput = secondInput.getText();
        
        
        double result;
        
        if(input.isEmpty() && Secondinput.isEmpty()){
            status.setText("You must enter values on those two input fields");
        }else{
            double firstValue = Double.parseDouble(input);
            double secondValue = Double.parseDouble(Secondinput);
            if(addVar.isSelected()){
            result = firstValue+secondValue;
            status.setText("Addition: "+result);
        }else if(subVar.isSelected()){
            result = firstValue-secondValue;
            status.setText("Substraction: "+result);
        }
        else if(mulVar.isSelected()){
            result = firstValue*secondValue;
            status.setText("Multiplication: "+result);
        }else if(divVar.isSelected()){
            result = firstValue/secondValue;
            status.setText("Division: "+result);
        }
        else{
            status.setText("You must select an operation");
        }
        }
    }//GEN-LAST:event_calculateBtnMouseClicked

    private void secondInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondInputActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void mulVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulVarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addVar;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JRadioButton divVar;
    private javax.swing.JTextField firstInput;
    private javax.swing.JRadioButton mulVar;
    private javax.swing.JTextField secondInput;
    private javax.swing.JLabel status;
    private javax.swing.JRadioButton subVar;
    // End of variables declaration//GEN-END:variables
}
